# File              : _config.yml
# Author            : tzhang
# Date              : 19.01.2021
# Last Modified Date: 19.01.2021
# Last Modified By  : tzhang
title: Small Modular Reactor Roadmap
description: Pridiction of SMR capacity from 2021 to 2050
plugins:
  - jekyll-remote-theme
remote_theme: poole/hyde

theme: jekyll-theme-minimal